current: target

target pngtarget pdftarget vtarget acrtarget: notarget

##################################################################

# make files

Sources = Makefile 

##################################################################

local = default
-include ../make/local.mk
include ../make/$(local).mk

