### Hooks for the editor to set the default target
current: target

target pngtarget pdftarget vtarget acrtarget: notarget

##################################################################

# make files

# local.mk should not be a source file; use it so reset the value of the variable local

Sources = Makefile 

##################################################################

md = ../make/

local = default
-include $(md)/local.mk
include $(md)/$(local).mk

